# Generated by Django 6.0.3 on 2026-04-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="isHR",
            field=models.BooleanField(default=True),
        ),
    ]
