# Generated by Django 6.0.3 on 2026-05-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_user_ishr"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default="", max_length=20, verbose_name="Телефон"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Почта"),
        ),
    ]
