# Generated by Django 6.0.3 on 2026-05-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isHR',
            field=models.BooleanField(default=True, verbose_name='HR'),
        ),
    ]
