# Generated by Django 6.0.3 on 2026-05-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancyAndCv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='content',
            field=models.TextField(blank=True, verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Загаловок'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='content',
            field=models.TextField(blank=True, verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Загаловок'),
        ),
    ]
