# Generated by Django 6.0.3 on 2026-04-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancyAndCv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="testField",
            field=models.TextField(blank=True),
        ),
    ]
