# Generated by Django 6.0.3 on 2026-04-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancyAndCv", "0002_vacancy_testfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="testField",
        ),
    ]
