# Generated by Django 6.0.3 on 2026-04-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancyAndCv", "0004_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="slug",
            field=models.SlugField(
                default=1, max_length=255, unique=True, verbose_name="URL"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vacancy",
            name="slug",
            field=models.SlugField(
                default=1, max_length=255, unique=True, verbose_name="URL"
            ),
            preserve_default=False,
        ),
    ]
