# Generated by Django 6.0.3 on 2026-04-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancyAndCv", "0005_cv_slug_vacancy_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="URL"
            ),
        ),
    ]
