# Generated by Django 6.0.3 on 2026-04-26 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancyAndCv", "0006_alter_cv_slug_alter_vacancy_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cvs",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vacancy",
            name="sendCV",
            field=models.ManyToManyField(
                related_name="vacancies", to="vacancyAndCv.cv"
            ),
        ),
    ]
