# Generated by Django 6.0.3 on 2026-05-09 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancyAndCv", "0007_cv_user_vacancy_sendcv"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_vacancies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
