# Generated by Django 6.0.3 on 2026-05-09 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vacancyAndCv", "0008_vacancy_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacancyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv_embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Векторное представление резюме",
                        null=True,
                    ),
                ),
                ("match_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="vacancyAndCv.cv",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="vacancyAndCv.vacancy",
                    ),
                ),
            ],
        ),
    ]
